name: mern-app

services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "5000:5000"

  client:
    build: 
      context: ./client
      target: production
      args:
        VITE_DEV_API_URL: ${VITE_DEV_API_URL}
        VITE_DOMAIN_NAME: ${VITE_DOMAIN_NAME}
        VITE_ENV: ${VITE_ENV}
    restart: unless-stopped
    env_file: ./client/.env
    environment:
      - VITE_DEV_API_URL=${VITE_DEV_API_URL}
      - VITE_DOMAIN_NAME=${VITE_DOMAIN_NAME}
      - VITE_ENV=${VITE_ENV}
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "5173:5173"
    command: npm start -- --host
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.testing:/etc/caddy/Caddyfile
      - caddy_data:/caddy_data
      - caddy_config:/caddy_config
    networks:
      - mern-app
    depends_on:
      - api
      - client

volumes:
  caddy_data:
  caddy_config:
networks:
  mern-app:
    driver: bridge