services:
  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    env_file: 
      - .env.${COMPOSE_ENV:-testing}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URI=${DATABASE_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - ./server_logs:/logs
    networks:
      - mern-app
    expose:
      - "5000"

  client:
    build: 
      context: ./client
      target: production
      args:
        - VITE_DEV_API_URL=${VITE_DEV_API_URL:-}
        - VITE_DOMAIN_NAME=${VITE_DOMAIN_NAME}
        - VITE_ENV=${VITE_ENV}
        - VITE_DOCKER_API_URL=${VITE_DOCKER_API_URL}
    restart: unless-stopped
    env_file:
      - .env.${COMPOSE_ENV:-testing}
    networks:
      - mern-app
    expose:
      - "5173"
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_DOMAIN_NAME=${VITE_DOMAIN_NAME}
    volumes:
      - ./caddy/Caddyfile.testing:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy
    networks:
      - mern-app
    depends_on:
      - api
      - client

volumes:
  caddy_data:
  caddy_config:
networks:
  mern-app:
    driver: bridge