const STATE_ABBREVIATIONS = {
  'Alabama': 'AL',
  'Alaska': 'AK',
  'Arizona': 'AZ',
  'Arkansas': 'AR',
  'California': 'CA',
  'Colorado': 'CO',
  'Connecticut': 'CT',
  'Delaware': 'DE',
  'Florida': 'FL',
  'Georgia': 'GA',
  'Hawaii': 'HI',
  'Idaho': 'ID',
  'Illinois': 'IL',
  'Indiana': 'IN',
  'Iowa': 'IA',
  'Kansas': 'KS',
  'Kentucky': 'KY',
  'Louisiana': 'LA',
  'Maine': 'ME',
  'Maryland': 'MD',
  'Massachusetts': 'MA',
  'Michigan': 'MI',
  'Minnesota': 'MN',
  'Mississippi': 'MS',
  'Missouri': 'MO',
  'Montana': 'MT',
  'Nebraska': 'NE',
  'Nevada': 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  'Ohio': 'OH',
  'Oklahoma': 'OK',
  'Oregon': 'OR',
  'Pennsylvania': 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  'Tennessee': 'TN',
  'Texas': 'TX',
  'Utah': 'UT',
  'Vermont': 'VT',
  'Virginia': 'VA',
  'Washington': 'WA',
  'West Virginia': 'WV',
  'Wisconsin': 'WI',
  'Wyoming': 'WY',
  'District of Columbia': 'DC',
  'American Samoa': 'AS',
  'Guam': 'GU',
  'Northern Mariana Islands': 'MP',
  'Puerto Rico': 'PR',
}

const OTHER_ABBREVIATIONS = {
  'Statewide': 'Stwd',
  'Voter': 'Vtr',
  'Survey': 'Svy',
  'Lake': 'Lk',
  'River': 'Rvr',
  'Stream': 'Strm',
  'Creek': 'Crk',
  'Bay': 'By',
  'Ocean': 'Oc',
  'Island': 'Isl',
  'Peninsula': 'Pen',
  'Mountain': 'Mtn',
  'Range': 'Rng',
  'Forest': 'Frst',
  'Park': 'Prk',
  'Wilderness': 'Wldns',
  'Wildlife': 'Wldlf',
  'Refuge': 'Rfg',
  'County': 'Cnty',
  'Cells': 'C',
  'State of the Rockies': 'StRkys',
  'State': 'St',
  'Rockies': 'Rkys',
  'Oversample': 'OS',
  'District': 'Dist',
  'Lower': 'Lwr',
  'Upper': 'Upr',
  'North': 'N',
  'South': 'S',
  'East': 'E',
  'West': 'W',
  'Central': 'C',
  'Northwest': 'NW',
  'Northeast': 'NE',
  'Southeast': 'SE',
  'Southwest': 'SW',
}

module.exports = {
  STATE_ABBREVIATIONS,
  OTHER_ABBREVIATIONS
}